services:
  backend:
    build: ./Backend
    container_name: bookstore-backend
    ports:
      - "4001:4001"
    env_file:
      - ./Backend/.env
    restart: unless-stopped

  frontend:
    build: ./Frontend
    container_name: bookstore-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped